version: '3.8'

services:
  sharebox-api:
    build: .
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - sharebox-db
    command: npm run dev
    networks:
      - sharebox-net

  sharebox-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sharebox-net

volumes:
  postgres_data:

networks:
  sharebox-net:
    driver: bridge